name: Build with Appflow

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v3
      
    - name: Setup java
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 17
        
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    
    - name: Install Cordova
      run: npm install -g cordova

    - name: Install Ionic
      run: npm install -g @ionic/cli

    - name: Install app dependencies
      run: npm install

    - name: Add Android platform
      run: ionic cordova platform add android@latest
