name: Build with Appflow

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  # This will build an IPA & Upload the artifact in iOS.zip
  build-android:
    runs-on: ubuntu-latest
    steps:
    - uses: sparkfabrik/android-build-action@v1.0.0
      with:
        project-path: android
        output-path: my-app.apk
        browserstack-upload: true
        browserstack-username: ${{ secrets.BROWSERSTACK_USERNAME }}
        browserstack-access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
